### ISSUE TITLE
MORNING SESSION CODE REVIEW

### ISSUE THREAD

**Issue by rachidelaid** [billionsjoel/todo-app#3]
### This PR suggests code reviews for the es6 awesome books app

- we suggest that you sort your array element in the sort function rather than having an entire module ex `arr.sort((a,b) => a.index-b.index)`.
- we suggest that use `forEach` instead of `map` if you are just going to loop through the array.
- we suggest that you pass the todos array as a parameter instead of redeclaring it in each module.
- we suggest that you call the `renderAllTasks` method every time you update your array that way you can avoid having the `renderTask` method.

**Comment by billionsjoel** [comment]
All issues fixed.
